### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by FisherCats** [mashijie1028/Happy-CGCD#4]
Hi, thank you for your excellent work, it's really helpful to understand C-GCD. I'm not sure which model is used in your project, could you please provide the pretrained backbone weights ?  That's will be great.

**Comment by mashijie1028** [comment]
Hi! Thanks for the question.
We use ViT-B/16, pre-trained with [DINO](https://github.com/facebookresearch/dino), which is the conventional implementation in the literature of GCD. You could download the pre-trained weights from the [original repo](https://github.com/facebookresearch/dino).

**Comment by FisherCats** [comment]
> Hi! Thanks for the question. We use ViT-B/16, pre-trained with [DINO](https://github.com/facebookresearch/dino), which is the conventional implementation in the literature of GCD. You could download the pre-trained weights from the [original repo](https://github.com/facebookresearch/dino).

OK, thanks a lot !
